DentalClinicWebsite/DentalClinicWebsite/Controllers/ContactController.cs
using System.Net.Mail;
using Microsoft.AspNetCore.Mvc;
using MimeKit;
using MailKit.Net.Smtp;
using DentalClinicWebsite.Models;
using MailKit.Security;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace DentalClinicWebsite.Controllers
{
    public class ContactController : Controller
    {
        private readonly IConfiguration _config;

    public ContactController(IConfiguration config)
        {
        _config = config;
    }

        public ActionResult Contact()
        {

            // Pass the list of appointments to the view
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SendMessage(Contact form)
        {
            if (ModelState.IsValid)
            {
                // Compose the message
                var message = new MimeMessage();
                message.From.Add(new MailboxAddress(form.Name, form.Email));
                message.To.Add(new MailboxAddress("Robert Nedelcu", "nedelcurobert62@gmail.com"));
                message.Subject = form.Subject;

                message.Body = new TextPart("plain")
                {
                    Text = form.Message
                };

                using (var client = new MailKit.Net.Smtp.SmtpClient())
                {
                    client.ServerCertificateValidationCallback = (s, c, h, e) => true;
                    client.Connect(_config["MailSettings:SmtpServer"], int.Parse(_config["MailSettings:SmtpPort"]), SecureSocketOptions.StartTls);
                    client.Authenticate(_config["MailSettings:Username"], _config["MailSettings:Password"]);
                    client.Send(message);
                    client.Disconnect(true);
                }

                TempData["SuccessMessage"] = "Mesajul a fost trimis cu succes!";
            }

            return View(form);
        }
    }
}

DentalClinicWebsite/DentalClinicWebsite/Controllers/PricesController.cs
using DentalClinicWebsite.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DentalClinicWebsite.Controllers
{
    public class PricesController : Controller
    {
        private readonly ITreatmentService _treatmentService;
        public PricesController(ITreatmentService treatmentService)
        {
            _treatmentService = treatmentService;
        }

        [AllowAnonymous]
        public IActionResult Prices()
        {
            var treatments = _treatmentService.GetAllTreatments();

            return View(treatments);
        }
    }
}

DentalClinicWebsite/DentalClinicWebsite/Controllers/TeamController.cs
using DentalClinicWebsite.Models;
using DentalClinicWebsite.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DentalClinicWebsite.Controllers
{
    public class TeamController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ISpecializationService _specializationService;
        public TeamController(UserManager<User> userManager,ISpecializationService specializationService)
        {
            _userManager = userManager;
            _specializationService = specializationService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Team()
        {
            var dentists = await _userManager.GetUsersInRoleAsync("Dentist");

            var specializationsDict = new Dictionary<string, IEnumerable<string>>();

            foreach (var dentist in dentists)
            {
                var specializations = await _specializationService.GetSpecializationsForDentist(dentist.Id);
                specializationsDict[dentist.Id] = specializations;
            }

            ViewBag.Specializations = specializationsDict;
            ViewBag.Dentists = dentists;

            return View(dentists);
        }
    }
}

DentalClinicWebsite/DentalClinicWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DentalClinicWebsite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DentalClinicWebsite.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <div class="logo-text">
            <img src="/img/logo3.png" alt="Logo SmileDent" style="display: inline-block;" class="logo" />
            <h1 class="logo-title">SmileDent</h1>
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Team" asp-action="Team">Echipa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Schedule" asp-action="Schedule">Programeaza-te</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="Services">Servicii</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prices" asp-action="Prices">Tarife</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Admin">Admin</a>
                            </li>                  
                        }
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Dentist") || User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MySchedules" asp-action="MySchedules">Programarile Mele</a>
                            </li>
                        }
                    </ul>
                    @if (TempData["Message"] != null)
                    {
                        <div id="success-login" class="alert alert-success" role="alert">
                            @TempData["Message"]
                        </div>

                        <script>
                            setTimeout(function () {
                                var successMessage = document.getElementById("success-login");
                                successMessage.parentNode.removeChild(successMessage);
                            }, 2000);
                        </script>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>